/**
 * Committed data for the public `/demo` route (card U1).
 *
 * `/demo` renders the full portfolio dashboard for a visitor with **no IND Money
 * account and no sign-in**, and its one non-negotiable property is that it makes
 * **no LLM call and no authenticated backend call, ever** — a public route that
 * generated narratives would let anonymous strangers burn OpenAI credit, and it
 * has to be instant. So every figure it draws is frozen into `dashboard.json`
 * and imported here at build time; the page performs zero `fetch`.
 *
 * `dashboard.json` is generated by `backend/scripts/gen_demo_dashboard.py`,
 * which runs the real stub connector through the real `/portfolio/*` serializers
 * and reshapes card A1's committed `overview.json`. It is 100% synthetic (the
 * invented stub portfolio in `backend/tests/fixtures/demo/`). Regenerate with:
 *
 *     cd backend && python -m scripts.gen_demo_dashboard
 */
import dashboard from "./dashboard.json";
import type { OverviewComplete, PortfolioHolding, PortfolioSummary } from "@/lib/api";

/**
 * One holdings bucket, pre-walked.
 *
 * The live dashboard fetches holdings per asset type the snapshot reported
 * (`app/portfolio/page.tsx::loadHoldings`); the generator performs that walk
 * once so `/demo` renders the same holdings table and the same EPF source-empty
 * callout (a bucket with a reported value but zero enumerable rows) without a
 * single request.
 */
export interface DemoBucket {
  assetType: string;
  assetTypeRaw: string | null;
  status: "ok";
  reportedValue: number | null;
  rows: PortfolioHolding[];
}

export interface DemoDashboard {
  summary: PortfolioSummary;
  buckets: DemoBucket[];
  overview: OverviewComplete;
}

/** The frozen demo dashboard. Synthetic; safe to render to anyone. */
export const demoDashboard = dashboard as unknown as DemoDashboard;
