"""initial identity tables

Creates the three F1 tables: users, broker_links, oauth_pending.

Both child tables carry `ON DELETE CASCADE` on their `user_id` FK, so a
`DELETE FROM users` removes the dependent rows inside Postgres — the
"delete my data" path must not depend on ORM-side cascade config.

Revision ID: 0001
Revises:
Create Date: 2026-08-15

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('broker_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('access_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('client_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('supports_refresh', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', name='uq_broker_links_user_source')
    )
    op.create_index(op.f('ix_broker_links_user_id'), 'broker_links', ['user_id'], unique=False)
    op.create_table('oauth_pending',
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('verifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('client_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_oauth_pending_user_id'), 'oauth_pending', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_pending_user_id'), table_name='oauth_pending')
    op.drop_table('oauth_pending')
    op.drop_index(op.f('ix_broker_links_user_id'), table_name='broker_links')
    op.drop_table('broker_links')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
