"""snapshot tables

Creates the three S1 tables: snapshot_days, snapshot_holdings, snapshot_raw.

Every FK carries `ON DELETE CASCADE` at the DB level: `snapshot_days.user_id`
to `users`, and both child tables' `snapshot_id` to `snapshot_days`. Deleting a
user therefore removes their entire net-worth history without the ORM being
involved — which is what L1's "delete my data" path depends on.

`UNIQUE (user_id, captured_on)` is not decoration: it is the idempotency
guarantee that makes the ~01:00 IST retry run a free no-op instead of a second
row for the same day.

Autogenerated, then reviewed: the `postgresql` dialect import below is added by
hand (`script.py.mako` only injects `sqlmodel`), without which this file raises
`NameError` on the JSONB column.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-16

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('usd_inr_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'captured_on', name='uq_snapshot_days_user_day')
    )
    op.create_index(op.f('ix_snapshot_days_user_id'), 'snapshot_days', ['user_id'], unique=False)
    op.create_table('snapshot_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('units', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('avg_cost', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_holdings_snapshot_id'), 'snapshot_holdings', ['snapshot_id'], unique=False)
    op.create_table('snapshot_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_raw_captured_at'), 'snapshot_raw', ['captured_at'], unique=False)
    op.create_index(op.f('ix_snapshot_raw_snapshot_id'), 'snapshot_raw', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_raw_snapshot_id'), table_name='snapshot_raw')
    op.drop_index(op.f('ix_snapshot_raw_captured_at'), table_name='snapshot_raw')
    op.drop_table('snapshot_raw')
    op.drop_index(op.f('ix_snapshot_holdings_snapshot_id'), table_name='snapshot_holdings')
    op.drop_table('snapshot_holdings')
    op.drop_index(op.f('ix_snapshot_days_user_id'), table_name='snapshot_days')
    op.drop_table('snapshot_days')
    # ### end Alembic commands ###
