"""snapshot day partiality marker

Adds `snapshot_days.buckets_failed` (JSONB, nullable): the asset types a capture
reported but could not read, as `[{"asset_type": …, "reason": …}, …]`.

**NULL means the capture was complete.** Without this column, a day written with
an unreadable bucket is indistinguishable from a day where that bucket was
genuinely empty — the rows are absent either way — and "you held nothing there"
is a false statement about someone's money rather than a missing log line.

It lives on `snapshot_days` rather than as a marker row in `snapshot_raw`
because `snapshot_raw` is pruned at 90 days while the day is kept forever: a
two-year-old partial capture whose evidence had been pruned would read as a
clean one.

Rows written before this migration are NULL and therefore read as complete.
That is accurate today — no production database exists yet — and is stated here
so a future reader does not mistake it for a guarantee about historical rows.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-16

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_days', sa.Column('buckets_failed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot_days', 'buckets_failed')
    # ### end Alembic commands ###
